version: "3.8"

services:
  app:
    image: lscr.io/linuxserver/grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - GROCY_CURRENCY
      - GROCY_FEATURE_FLAG_STOCK
      - GROCY_FEATURE_FLAG_SHOPPINGLIST
      - GROCY_FEATURE_FLAG_RECIPES
      - GROCY_FEATURE_FLAG_CHORES
      - GROCY_FEATURE_FLAG_TASKS
      - GROCY_FEATURE_FLAG_BATTERIES
      - GROCY_FEATURE_FLAG_EQUIPMENT
      - GROCY_FEATURE_FLAG_CALENDAR
      - GROCY_FEATURE_FLAG_LABEL_PRINTER
    volumes:
      - grocy_conf:/config
    restart: unless-stopped
    networks:
      default:
      proxy_apps:

volumes:
  grocy_conf:

networks:
  proxy_apps:
    name: proxy_apps
    external: true

